// data_images.js - Images des poissons (avant/après capture) par catégorie
// Généré à partir des liens fournis (SOZ-FiveM-Assets)
const FISH_IMAGES = {
    standard: {
        "Petite Grosse Baleine": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/petite_grosse_baleine.webp",
        "Pfister Fish": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/pfister_fish.webp",
        "Barrycuda": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/barrycuda.webp",
        "Angry Fish": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/angry_fish.webp",
        "Cristalfish": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/cristalfish.webp",
        "Le Poulpe Thor": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/le_poulpe_thor.webp",
        "Glowriffy": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/glowriffy.webp",
        "Carpe Diam": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/carpe_diam.webp",
        "Chibhippocampe": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/chibhippocampe.webp",
        "Stepafou Moustachou": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/stepafou_moustachou.webp",
        "Graie Montas": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/graie_montas.webp",
        "Carpotresor": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/carpotresor.webp",
        "Hypnoisson": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/hypnoisson.webp",
        "Meduze De Fe De La Morre Qui Tu": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/meduze_de_fe_de_la_morre_qui_tu.webp",
        "Marine": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/marine.webp",
        "Purple Omen": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/purple_omen.webp",
        "Bigornoob": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/bigornoob.webp",
        "Le Sunny": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/le_sunny.webp",
        "Croaky Froggy": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/croaky_froggy.webp",
        "Chaxo": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/chaxo.webp",
        "Morpheus Somnolent": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/morpheus_somnolent.webp",
        "Portinet": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/portinet.webp",
        "La Clebsouille": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/la_clebsouille.webp",
        "Fichouette": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/fichouette.webp",
        "Merou Colerique Tachete": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/merou_colerique_tachete.webp",
        "Chromabranchus Virosa": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/chromabranchus_virosa.webp",
        "Mossiferne": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/mossiferne.webp",
        "Figel": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/figel.webp",
        "Rosailee": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/rosailee.webp",
        "Le Perlea": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/le_perlea.webp",
        "Sanajvit": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/sanajvit.webp",
        "Simone": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/simone.webp",
        "Axowin Dragonnet Splendide": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/axowin_dragonnet_splendide.webp",
        "Fire Plouf": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/fire_plouf.webp",
        "Aquatic Wood Runner": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/aquatic_wood_runner.webp",
        "Squalopoisson": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/squalopoisson.webp",
        "Rastortue": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/rastortue.webp",
        "Voile Souvenir": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/voile_souvenir.webp",
        "Sandre Florale": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/sandre_florale.webp",
        "Pinky Punky Fish": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/pinky_punky_fish.webp",
        "Electropoulpe": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/electropoulpe.webp",
        "Verdipoulpe": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/verdipoulpe.webp",
        "Pilulieu": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/pilulieu.webp",
        "Orions Star": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/orions_star.webp",
        "Globenciel": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/globenciel.webp",
        "Poissoncisson": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/poissoncisson.webp",
        "Le Pipoulpe": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/le_pipoulpe.webp",
        "Luminosa": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/luminosa.webp",
        "Poulamar": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/poulamar.webp",
        "Electraie": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/electraie.webp",
        "Bolingbroke Fish": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/bolingbroke_fish.webp",
        "Nebulith": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/nebulith.webp",
        "Mariusson": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/mariusson.webp",
        "Dobbry Rok": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/dobbry_rok.webp",
        "Ablyssus": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/ablyssus.webp",
        "Zirvine Dracopis": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/zirvine_dracopis.webp",
        "Gobie Vaseux": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/gobie_vaseux.webp",
        "Trashark": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/trashark.webp",
        "Akumaaaa": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/akumaaaa.webp",
        "Lantrole": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/lantrole.webp",
        "La Crevette Arc En Ciel": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/la_crevette_arc_en_ciel.webp",
        "Acuattus": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/acuattus.webp",
        "Crabantine": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/crabantine.webp",
        "Blobo Acanthus": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/blobo_acanthus.webp",
        "Fausse Meduse Haploida": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/fausse_meduse_haploida.webp",
        "Bi Queue": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/bi_queue.webp",
        "Reggaetoad": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/reggaeToad.webp",
        "Hippocon": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/hippocon.webp",
        "Piranha Clown": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/piranha_clown.webp",
        "Coelacant": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/coelacant.webp",
        "Flannochet Zebre": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/flannochet_zebre.webp",
        "Baleine Iris": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/baleine_iris.webp",
        "Crabe Rubis": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/crabe_rubis.webp",
        "Carpe Emeraude": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/carpe_emeraude.webp",
        "Calmar Amethyste": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/calmar_amethyste.webp",
        "Meduse Ambre": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/meduse_ambre.webp",
        "Etoile Diamant": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/etoile_diamant.webp",
        "Tortue Saphir": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/tortue_saphir.webp",
        "Twinfish": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/twinfish.webp",
        "Happygloby": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/happygloby.webp",
        "Toxiglue": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/toxiglue.webp",
        "Octoleon": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/octoleon.webp",
        "Cryscrab": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/cryscrab.webp",
        "Rainbowfish": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/rainbowfish.webp",
        "Lumiscale": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/lumiscale.webp",
        "Athenais La Meduse Papillon": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/athenais_la_meduse_papillon.webp",
        "Uhane": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/uhane.webp",
        "Rubis Des Mers": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/rubis_des_mers.webp",
        "Lumeine": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/lumeine.webp",
        "Discoelacanthe": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/discoelacanthe.webp",
        "Cochon De Mer": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/cochon_de_mer.webp",
        "Zeponge De Mer": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/zeponge_de_mer.webp",
        "Goldecrevisse": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/goldecrevisse.webp",
        "Etoile De Merdeeeee Aie Elle Ma Mordu": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/etoile_de_merdeeeee_aie_elle_ma_mordu.webp",
        "Exocet Bleu": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/exocet_bleu.webp",
        "Poulpitrol": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/poulpitrol.webp",
        "Nimo": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/nimo.webp",
        "Tetrotox": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/tetrotox.webp",
        "Lapollo": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/lapollo.webp",
        "Kronk Terreur": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/kronk_terreur.webp",
        "Poulpe Eclair": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/poulpe_eclair.webp",
        "Lotushell": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/lotushell.webp",
        "Icecrevisse": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/icecrevisse.webp",
        "Frostoad": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/frostoad.webp",
        "Carpxolotl": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/carpxolotl.webp",
        "Clearcrab": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/clearcrab.webp",
        "Wooden Flight": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/wooden_flight.webp",
        "Horaine Argentee": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/horaine_argentee.webp",
        "Doradonut": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/doradonut.webp",
        "Oursin Kipik": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/oursin_kipik.webp",
        "Silver Moula": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/silver_moula.webp",
        "Golden Huitre": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/golden_huitre.webp",
        "Crevette Alecto": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/crevette_alecto.webp",
        "Limasse": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/limasse.webp",
        "Poimousse": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/poimousse.webp",
        "Goofysh": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/goofysh.webp",
        "Carpe Feur": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/carpe_feur.webp",
        "Carpe A Jouer": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/carpe_a_jouer.webp",
        "Homard Indigo Saxicole": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/homard_indigo_saxicole.webp",
        "Flabellina": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/flabellina.webp",
        "Comtecombre De Mer": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/comtecombre_de_mer.webp",
        "Noctiscale": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/noctiscale.webp",
        "Luninja": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/luninja.webp",
        "Saumon": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/saumon.webp",
        "Greg": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/greg.webp",
        "Pleutrisson": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/pleutrisson.webp",
        "Mousseton": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/mousseton.webp",
        "Cocqueluchard A Crete Rouge": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/cocqueluchard_a_crete_rouge.webp",
        "Bar A Thym": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/bar_a_thym.webp",
        "Carassin Tropical": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/carassin_tropical.webp",
        "Demoiselle Maraichere": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/demoiselle_maraichere.webp",
        "Kokoro Spumeux": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/kokoro_spumeux.webp",
        "Origafish": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/origafish.webp",
        "Zeta Membraneux": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/zeta_membraneux.webp",
        "Dragon Des Mers": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/dragon_des_mers.webp",
        "Mi-Octo Grandmax": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/mi-octo_grandmax.webp",
        "Crobrail": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/crobrail.webp",
        "Draquaticus": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/draquaticus.webp",
        "Abherus Le Dentu": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/abherus_le_dentu.webp",
        "Mur Haine": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/mur_haine.webp",
        "Tyrannus Piscis": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/tyrannus_piscis.webp",
        "Grincheux Cramoisi": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/grincheux_cramoisi.webp",
        "Blogogloblo": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/blogogloblo.webp",
        "Fishy Duck": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/fishy_duck.webp",
        "La Sardynamite": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/la_sardynamite.webp",
        "Fluroralia Nocturne": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/fluroralia_nocturne.webp",
        "Petit Poulpe Royal": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/petit_poulpe_royal.webp",
        "Tortue Imperiale": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/tortue_imperiale.webp",
        "Tort Aily": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/tort_aily.webp",
        "Draceen": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/draceen.webp",
        "Tribow": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/tribow.webp",
        "Angryd O": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/angryd_o.webp",
        "Petit Dragon Des Mers": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/petit_dragon_des_mers.webp",
        "Langostazul": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/langostazul.webp",
        "Happyd O": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/happyd_o.webp",
        "Le Pasne": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/le_pasne.webp",
        "Chelonienseparables": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/chelonienseparables.webp",
        "Yuko": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/yuko.webp",
        "Reinette": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/reinette.webp",
        "Arguyere Bicephale": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/arguyere_bicephale.webp",
        "Berger De Floride": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/berger_de_floride.webp",
        "Elicie Californien": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/elicie_californien.webp",
        "Exocet Colibri": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/exocet_colibri.webp",
        "Exocet Oriental": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/exocet_oriental.webp",
        "Exocet Sardine": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/exocet_sardine.webp",
        "Finette": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/finette.webp",
        "Hampe-Noire Albinos": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/hampe-noire_albinos.webp",
        "Iridesce Cyclope": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/iridesce_cyclope.webp",
        "Jolicoeur Smaragdin": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/jolicoeur_smaragdin.webp",
        "Mouchi Papillon": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/mouchi_papillon.webp",
        "Perche Leopard": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/perche_leopard.webp",
        "Qazoar Antique": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/qazoar_antique.webp",
        "Rondouille Gibeuse": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/rondouille_gibeuse.webp",
        "Saumon D Andreas": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/saumon_d_andreas.webp",
        "Tribion Carrele": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/tribion_carrele.webp",
        "Urgule": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/urgule.webp",
        "Vannole Cameleon": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vannole_cameleon.webp",
        "William": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/william.webp",
        "Xazatas": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/xazatas.webp",
        "Silverfish": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/silverfish.webp",
        "L Aubergine Marine": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/l_aubergine_marine.webp",
        "Le Poisson Prismatique": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/le_poisson_prismatique.webp",
        "Le Nageoires D Azur": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/le_nageoires_d_azur.webp",
        "La Petite Gemme Marine": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/la_petite_gemme_marine.webp",
        "Hotfeather": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/hotfeather.webp",
        "Grab": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/grab.webp",
        "Tardaud": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/tardaud.webp",
        "Anemone Printaniere": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/anemone_printaniere.webp",
        "Amalgatine": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/amalgatine.webp",
        "Ourou Beerus": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/ourou_beerus.webp"
    },
    summer: {
        "Bernartorite": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_bernartorite.webp",
        "Dunequartz Fossilfin": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_dunequartz_fossilfin.webp",
        "Crabicruz": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_crabicruz.webp",
        "Angrille Flamboyante": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_angrille_flamboyante.webp",
        "Amberichthys Crystallinus": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_amberichthys_crystallinus.webp",
        "Caillouflage": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_caillouflage.webp",
        "Épavomorphus": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_epavomorphus.webp",
        "Moule Quartzine": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_moule_quartzine.webp",
        "Le Lavaloup": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_le_lavaloup.webp",
        "Éponge Dunaire": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_eponge_dunaire.webp",
        "Corallium Cementatus": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_corallium_cementatus.webp",
        "Négador Sableux": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_negador_sableux.webp",
        "Spectrocarne": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_spectrocarne.webp",
        "Trilobitrix Fatalis": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_trilobitrix_fatalis.webp",
        "Escaflamme": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_escaflamme.webp",
        "Smaragdus Tristulus": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_smaragdus_tristulus.webp",
        "Cendrier": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_cendrier.webp",
        "Koi-sandré": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_koi_sandre.webp",
        "Crabctus": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_crabctus.webp",
        "Pagurus Quarziticus": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_pagurus_quarziticus.webp",
        "Cactifish": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_cactifish.webp",
        "Lithogemme": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_lithogemme.webp",
        "Cristallus Hermitus": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_cristallus_hermitus.webp",
        "Maugrim fluorescent": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_maugrim_fluorescent.webp",
        "Jellylava": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_jellylava.webp",
        "Cactobulle": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_cactobulle.webp",
        "Terracripte": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_terracripte.webp",
        "Ecrelice": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_ecrelice.webp",
        "Astrocarnis": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_astrocarnis.webp",
        "Cutilice": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_cutilice.webp",
        "Tortoasis": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_tortoasis.webp",
        "Shelly Fish": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_helly_fish.webp",
        "Cactiblob": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_cactiblob.webp",
        "Sabléon": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_sableon.webp",
        "L'Ancre de Dune": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_ancre_de_dune.webp",
        "Mirage des Dunes": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_mirage_des_dunes.webp",
        "Sandtigerius Sableux": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_sandtigerius_sableux.webp",
        "Cactaceaphis Echinus": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_cactaceaphis_echinus.webp",
        "Quartzarctos Sableux": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_quartzarctos_sableux.webp",
        "Arenaphis Sédimentarius": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_arenaphis_sedimentarius.webp",
        "Sablonneux Cristallin": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_sablonneux_cristallin.webp",
        "Croc-Sable Abyssal": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_croc_sable_abyssal.webp",
        "Érodeur Cristallin": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_erodeur_cristallin.webp",
        "Mirage-Fossile Vorace": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_mirage_fossile_vorace.webp",
        "Limon-Caverne Dévoreur": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_limon_caverne_devoreur.webp",
        "Sablivor": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_sablivor.webp",
        "Ravageur Abyssal": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_ravageur_abyssal.webp",
        "Mirage Vorace": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_mirage_vorace.webp",
        "Verrequartz Spectral": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_verrequartz_spectral.webp",
        "Verméduse": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_vermeduse.webp",
        "Crabolith": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_crabolith.webp",
        "Nasty Gator": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_nasty_gator.webp",
        "Eclastae": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_eclastae.webp",
        "Oracle Gluant": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_oracle_gluant.webp",
        "Biblob": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_biblob.webp",
        "Clairétoile": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_clairetoile.webp",
        "Driffy": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_driffy.webp",
        "Ocre Topus": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_ocher_topus.webp",
        "Shineel": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_shineel.webp",
        "Fosshelix": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_fosshelix.webp",
        "Hippocorn": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_hippocorn.webp",
        "Mariusorite": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_mariusorite.webp",
        "Kayou": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_kayou.webp",
        "McShellface": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_mcshellface.webp",
        "Delphini Viera": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_delphini_viera.webp",
        "Medusa Galactica": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_medusa_galactica.webp",
        "Sandstormy": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_sandstormy.webp",
        "Radiambra": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_radiambra.webp",
        "Obscurafangus": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_obscurafangus.webp",
        "Savantus": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_savantus.webp",
        "Carbo Brachyura": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_carbo_brachyura.webp",
        "Eunice aphroditois Argentum": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_eunice_aphroditois_argentum.webp",
        "Rubrum Ferrum": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_rubrum_ferrum.webp",
        "Pitris Aeris": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_pitris_aeris.webp",
        "Aurum Asterias": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_aurum_asterias.webp",
        "Bismuth Testa": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_bismuth_testa.webp",
        "Balaenidae Mineralis": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_balaenidae_mineralis.webp",
        "Fongiflou": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_fongiflou.webp",
        "Sonochino Sadame": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_sonochino_sadame.webp",
        "Escargoldorak": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_escargoldorak.webp",
        "Quartzillon": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_quartzillon.webp",
        "Octorok": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_octorok.webp",
        "Aridokraken": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_aridokraken.webp",
        "Kipikoku": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_kipikoku.webp",
        "Globlune": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_globlune.webp",
        "Rectus Rictus": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_rectus_rictus.webp",
        "John-à-tan": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_john_a_tan.webp",
        "L'Astérocoque": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_asterocoque.webp",
        "Géant Vert des sables à piquants": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_geant_vert.webp",
        "Floracanthus": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_floracanthus.webp",
        "Woody": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_woody.webp",
        "Shiny McTentacles": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_shiny_mctentacles.webp",
        "Sedimentor": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_sedimentor.webp",
        "Géocryne": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_geocryne.webp",
        "Sandy": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_sandy.webp",
        "Bétippocampe": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_betippocampe.webp",
        "Spikybulle": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_spikybulle.webp",
        "Quartzine": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_quartzine.webp",
        "Karmonite": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_karmonite.webp",
        "Le Faux-Mignon": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_faux_mignon.webp",
        "Limabus": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_limabus.webp",
        "Fossilodon": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_fossilodon.webp",
        "Blue Crystal": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_blue_crystal.webp",
        "Sablonide": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_sablonide.webp",
        "Duneshark": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_duneshark.webp",
        "Cristarin": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_cristarin.webp",
        "Gustfish": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_gustfish.webp",
        "Delphini Aora": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_delphini_aora.webp",
        "Cristalina": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_cristalina.webp",
        "Sédicendre": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_sedicendre.webp",
        "Coquroche": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_coquroche.webp",
        "Sablefin": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_sablefin.webp",
        "Lord Keos": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_lord_keos.webp",
        "Abyssocavernus ocrelimonensis": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_abyssocavernus.webp",
        "Pépéronius Fumantis": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_peperonius.webp",
        "Blossom Fisherry": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/summer_blossom_fisherry.webp"
    },
    halloween: {
        "Horrostine": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_horrostine.webp",
        "Cycrabe": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_cycrabe.webp",
        "Neostraceae horribilis": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_neostraceae_horribilis.webp",
        "Pagure Rouge": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_pagure_rouge.webp",
        "Zilure Démoniaque": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_zilure_demoniaque.webp",
        "Squalus Infernalis": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_squalus_infernalis.webp",
        "Fantocéan": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_fantocean.webp",
        "Langue de Satan": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_langue_de_satan.webp",
        "Toxzoguille": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_toxzoguille.webp",
        "Melusgnark": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_melusgnark.webp",
        "Krakenos": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_krakenos.webp",
        "Chirobyssus": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_chyrobissus.webp",
        "Nécrocrampe": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_necrocampe.webp",
        "Piranhéon": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_piranheon.webp",
        "Crustadémon": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_crustademon.webp",
        "Octohydra Nocturne": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_octohydra_nocturne.webp",
        "Abyssodémon": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_abyssodemon.webp",
        "Crustamortis": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_crustamortis.webp",
        "Oculymphe": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_oculymphe.webp",
        "Nécromurène": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_necromurene.webp",
        "Marécaille": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_marecaille.webp",
        "Nécrotriton": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_necrotriton.webp",
        "Zombicetus": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_zombiecetus.webp",
        "Krueger des Abysses": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_krueger_des_abyss.webp",
        "Larve de Xénocrevisse": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_larve_de_xenocrevisse.webp",
        "Xénocrevisse": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_xenocrevisse.webp",
        "Corail Nécroscière": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_corail_necrosclere.webp",
        "Mycrable": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_mycrable.webp",
        "Poisson Clown Clown": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_poisson_clown_clown.webp",
        "Bleurk": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_bleurk.webp",
        "Nagabyssale": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_nagabyssale.webp",
        "Candy Jelly-Fish": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_candy_jelly_fish.webp",
        "Zoctulus": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_zoctulus.webp",
        "Barracroutta": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_barracroutta.webp",
        "Ba-te-raie": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_batteraie.webp",
        "Nagazkill": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_nagazkill.webp",
        "Poisson citrouille": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_poisson_citrouille.webp",
        "Cranaraigné": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_cranaraignee.webp",
        "Crapamanite": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_crapamanite.webp",
        "Crapaud d'or": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_crapeau_or.webp",
        "Anibaltortle": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_anibaltortle.webp",
        "Maglimace": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_maglimace.webp",
        "Zombaleine": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_zombaleine.webp",
        "Mawgma": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_mawgma.webp",
        "Cravone": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_cravone.webp",
        "Fusiotonik": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_fusionotik.webp",
        "Zombéscargot": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_zombescargot.webp",
        "Sisilione": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_sisilione.webp",
        "Vampirescargot": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_vampiscargot.webp",
        "Machoire d'Hades": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_machoire_hades.webp",
        "Millipop": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_millipop.webp",
        "Necrojiko": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_necrojiko.webp",
        "Redhug": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_redhug.webp",
        "Damned Stinger": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_damned_stinger.webp",
        "Swimming Dead": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_swimming_dead.webp",
        "Kokichonk": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/halloween_kokichonk.webp"
    },
    bloodlust: {
        "Lamia Abyssal": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_la_lamia_abyssal.webp",
        "Vampiranha": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_vampiranha.webp",
        "Salmon Salvator": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_salmon_salvatore.webp",
        "Scyphozoa Draculea": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_scyphozoa_draculea.webp",
        "Sanguiscale": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_sanguisquale.webp",
        "Noctakan": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_noctakan.webp",
        "Dracupointius": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_dracupointius.webp",
        "Lilith des Abysses": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_lilith_des_abysses.webp",
        "Nosferictis": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_nosferictis.webp",
        "Tarentatu": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_tentaratu.webp",
        "Suskipeu": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_suskipeu.webp",
        "Goule Nosfératique": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_goule_nosferatique.webp",
        "Abyssolac": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_abyssolac.webp",
        "Fatalysiris": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_fatalysiris.webp",
        "Draculac": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_draculac.webp",
        "Méduse Spectrale": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_meduse_spectrale.webp",
        "Spectre de la Nuit": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_spectre_de_la_nuit.webp",
        "Vampiracine": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_vampiracine.webp",
        "Sanguivore des Abysses": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_sanguivore_des_abysses.webp",
        "Ancien des Abysses": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_ancien_des_abysses.webp",
        "Banfish": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_la_banfish.webp",
        "Axodrac": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_axodrac.webp",
        "Seichépire": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_seichepire.webp",
        "Goulejon": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_goulejon.webp",
        "Selviana": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_selviana.webp",
        "Hippocalypse": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_hippocalypse.webp",
        "Linceus Mysticus": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_linceus_mysticus.webp",
        "Crapaula": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_crapaula.webp",
        "Bernard Sanguinaire": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_bernard_le_sanguinaire.webp",
        "Obscuralma": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_obscuralma.webp",
        "Draculea": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_draculea.webp",
        "Hipporoquet": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_hipporoquet.webp",
        "Hémolux": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_hemolux.webp",
        "Hippoglycémy": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_hippoglycemy.webp",
        "Nosferay": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_nosferay.webp",
        "Spectre Sanguin": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_spectre_sanguin.webp",
        "L'immortel": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_l_immortel.webp",
        "Spectrophage": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_spectrophage.webp",
        "Ghosty": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_ghosty.webp",
        "Goule de Lince": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_goule_de_lince.webp",
        "Léanodon": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_leanodon.webp",
        "Vampiron des Abysses": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_le_vampiron_des_abysses.webp",
        "Spectrangle": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_spectrangle.webp",
        "Glouglouglou": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_gouglouglou.webp",
        "Grognonfou": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_grognonfrou.webp",
        "Abyssodon": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_abyssodon.webp",
        "Thalassogardien": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_thalassogardien.webp",
        "Crocobscur": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_crocbscur.webp",
        "Odeleko Dortoka": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_odoleko_dortoka.webp",
        "Dracus Andreacus": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_dracus_andreacus.webp",
        "Bullanis Draculea": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_bullanis_draculea.webp",
        "Cranium Fugu": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_cranium_fugu.webp",
        "Basileus Petrificat": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/vampire_basileus_petrificat.webp"
    },
    horizon: {
        "Glaciot": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_glaciot.webp",
        "Glagla": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_glagla.webp",
        "Poulpolar": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_poulpolar.webp",
        "Glacianguille": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_glacianguille.webp",
        "Givrétoile": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_givretoile.webp",
        "Krillige": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_krillige.webp",
        "Floconquille": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_floconquille.webp",
        "Cryostèle": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_cryostele.webp",
        "Pierre noir": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_pierre.webp",
        "Lundralith": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_lundralith.webp",
        "Polipluche": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_polipluche.webp",
        "Cryonéon": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_cryoneon.webp",
        "Flocibulle": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_flocibulle.webp",
        "Frigorath": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_frigorath.webp",
        "Frystal": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_frystal.webp",
        "Frisalis": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_frisalis.webp",
        "Frostusque": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_frostusque.webp",
        "Glacélion": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_glacelion.webp",
        "Glacérin": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_glacerin.webp",
        "Neosquilla": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_neosquilla.webp",
        "Polyglacis": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_polyglacis.webp",
        "Turtarctis": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_turtarctis.webp",
        "Blobivern": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_blobivern.webp",
        "Glaglaféfroid": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_glaglafefroid.webp",
        "Turboscargot": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_turboscargo.webp",
        "Frosted Eyebrow": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_frosted_eyebrow.webp",
        "Cryoplancton": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_cryoplancton.webp",
        "Laboreale": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_laboreale.webp",
        "Mélusine": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_melusine.webp",
        "Crabicy": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_crabbicy.webp",
        "Cryono": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_cryono.webp",
        "Temptotis": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_temptotis.webp",
        "Crocgivre": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_crogivr.webp",
        "Ecrin de gel": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_ecrin_de_gel.webp",
        "Luminara": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_luminara.webp",
        "Blizzarck": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_blizzarck.webp",
        "Astralux": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_astralux.webp",
        "Givrela": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_givrella.webp",
        "Poisson Glacique": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_poisson_glacique.webp",
        "Lucyole": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_lucyole.webp",
        "Fulgora": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_fulgora.webp",
        "Aile de Givre": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_aile_de_givre.webp",
        "Croc de givre": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_crocs_de_givre.webp",
        "Louphoque de glace": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_louphoque_de_glace.webp",
        "Aqualios": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_aqualios_givranthis.webp",
        "Griffe des glaces": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_griffe_des_glaces.webp",
        "Cryomedusa": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_cryomedusa_borealis.webp",
        "Cryospina": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_cryospina_glacialis.webp",
        "Petit iceberg": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_petit_iceberg.webp",
        "Etoile polaire": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_etoile_polaire.webp",
        "Artocrabe": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_arctocrabe_silens.webp",
        "Nymphe Cristaline": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_nymphe_cristalline.webp",
        "Glacivena Serpens": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_glacivena_serpens.webp",
        "Crylobite": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_crylobite_glacialis.webp",
        "Polaris Borealis": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_polaris_borealis.webp",
        "Abyssios": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_abyssios.webp",
        "Abyssis": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_abyssis.webp",
        "Iceoloth": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_l_iceolotl.webp",
        "Glacius Rex": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_glacius_rex.webp",
        "Araignée de mer": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_glaraignee_de_mer.webp",
        "Permafrost": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_permasfrost.webp",
        "Caerulius": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_caerulus_glacies.webp",
        "Piraglagla": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_piraglagla.webp",
        "Solarius": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_solarius.webp",
        "Aurorine": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_aurorine.webp",
        "Frigoris": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_frigoris.webp",
        "Torticube": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_turticube.webp",
        "Frygobyte": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_frigobyte.webp",
        "Abysalite": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_abyssalithe.webp",
        "Poulpice": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_poulpice.webp",
        "Nuagette": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_nuagette.webp",
        "Pirapaténis": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_pirapatrenice.webp",
        "Crysalon": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_crysalon.webp",
        "Glacérai argenté": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_glaceraie_argentee.webp",
        "Axofrost": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_axofrost.webp",
        "Ice Athan": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_ice.webp",
        "Orelys": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_orelys.webp",
        "Givreluisant": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_givreluisant.webp",
        "Vagabond Abyssal": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_vagabond_abyssal.webp",
        "Cryosquelette": "https://raw.githubusercontent.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Assets/oss/images/items/winter_cryosquelette.webp"
    }
};

// Retourne l'URL de l'image d'un poisson pour une catégorie donnée, ou null si absente
function getFishImage(category, nom) {
    return (FISH_IMAGES[category] && FISH_IMAGES[category][nom]) || null;
}
